name: Tilføj ny platform
description: Anmod om at tilføje en ny platform til Portaler
title: "Tilføj platform: "
labels:
  - platform-request
assignees: ["edbpede"]

body:
  - type: markdown
    attributes:
      value: |
        # 🎉 Tak for din interesse i at tilføje en ny platform!

        Vi vil gerne gøre det så nemt som muligt at tilføje nye platforme til Portaler. 
        Udfyld venligst nedenstående information så detaljeret som muligt.

        ---

  - type: input
    id: platform-name
    attributes:
      label: "📚 Platformnavn"
      description: "Hvad hedder den digitale læringsplatform?"
      placeholder: "F.eks. Dansk (0-2) eller Matematik Grundbog"
    validations:
      required: true

  - type: input
    id: publisher
    attributes:
      label: "🏢 Udgiver"
      description: "Hvem udgiver platformen?"
      placeholder: "F.eks. Gyldendal eller Alinea"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: "🔗 Platform URL"
      description: "Hvad er platformens webadresse?"
      placeholder: "F.eks. https://dansk0-2.gyldendal.dk"
    validations:
      required: true

  - type: dropdown
    id: subject
    attributes:
      label: "📖 Fag"
      description: "Hvilket fag hører platformen til?"
      options:
        - billedkunst
        - biologi
        - dansk
        - engelsk
        - fransk
        - fysik-kemi
        - geografi
        - håndværk-design
        - historie
        - idræt
        - kristendom
        - madkundskab
        - matematik
        - musik
        - natur-teknologi
        - samfundsfag
        - tysk
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 🎨 Ikon Indstillinger
        Du kan tilpasse ikonet for denne platform. Hvis du ikke angiver et ikon, vil der blive brugt standardikonet for faget.

  - type: checkboxes
    id: icon-overwrite
    attributes:
      label: "🖌️ Brug brugerdefineret ikon?"
      description: "Marker dette, hvis du vil bruge et andet ikon end standardikonet for faget"
      options:
        - label: "Brug brugerdefineret ikon"
          required: false

  - type: input
    id: icon-name
    attributes:
      label: "🖼️ Ikon navn"
      description: "Navnet på ikonet fra Phosphor Icons (f.eks. 'ph:book-bookmark-fill')"
      placeholder: "ph:book-bookmark-fill"
    validations:
      required: false

  - type: input
    id: icon-color
    attributes:
      label: "🎨 Ikon farve"
      description: "Tailwind CSS farveklasse (f.eks. 'text-blue-500')"
      placeholder: "text-blue-500"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 📚 Klassetrin
        Vælg de klassetrin som platformen er relevant for:

  - type: checkboxes
    id: grades
    attributes:
      label: "🎓 Klassetrin"
      description: "Vælg de klassetrin som platformen er relevant for"
      options:
        - label: "🎓 0. klasse"
        - label: "🎓 1. klasse"
        - label: "🎓 2. klasse"
        - label: "🎓 3. klasse"
        - label: "🎓 4. klasse"
        - label: "🎓 5. klasse"
        - label: "🎓 6. klasse"
        - label: "🎓 7. klasse"
        - label: "🎓 8. klasse"
        - label: "🎓 9. klasse"

  - type: textarea
    id: description
    attributes:
      label: "📝 Kort beskrivelse"
      description: "Giv en kort, præcis beskrivelse af platformen (1-2 sætninger)"
      placeholder: "F.eks.: Digital læringsplatform til dansk fra 0.-2. klasse med fokus på læseforståelse og skriftlig fremstilling."
    validations:
      required: true

  - type: textarea
    id: long-description
    attributes:
      label: "📋 Detaljeret beskrivelse"
      description: "Beskriv platformens funktioner, anvendelsesmuligheder og indhold mere detaljeret"
      placeholder: |
        F.eks.:
        - Hvilke specifikke læringsmål understøtter platformen?
        - Hvilke særlige funktioner eller værktøjer indeholder den?
        - Hvordan kan den bruges i undervisningen?
        - Er der særlige fordele eller unikke aspekter ved platformen?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ✨ Tak for din tid! Vi gennemgår din anmodning hurtigst muligt.
