name: Setup Repository Labels

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/ISSUE_TEMPLATE/**'
    branches:
      - main

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create required labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              {
                name: 'platform-request',
                color: '0052CC',
                description: 'Request to add a new platform'
              },
              {
                name: 'automated-pr',
                color: '2ECC40',
                description: 'Pull request created by automation'
              }
            ];

            for (const label of labels) {
              try {
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name
                });
                console.log(`Label ${label.name} already exists`);
              } catch (error) {
                if (error.status === 404) {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description
                  });
                  console.log(`Created label ${label.name}`);
                } else {
                  console.error(`Error checking label ${label.name}:`, error);
                }
              }
            }
